### PR TITLE
Rewrite iOS with swift

### PR DESCRIPTION
**Pull request by saeedkargosha**
1-rewrite all function iOS with swift
2-add function for generating EC
3-add function for generating CSR
4-add function for getting PublicKey with DER
5-export Constance ECDSA algorithm

### CODE REVIEW

**Comment by amitaymolko** [comment]
Hey @saeedkargosha 
Thanks for this!
Does this PR close https://github.com/amitaymolko/react-native-rsa-native/pull/69 ?

**Comment by saeedkargosha** [comment]
you're welcome
Yeah.

**Comment by Ben305** [comment]
👍 

@amitaymolko Any chance to get this merged and released soon?

**Comment by amitaymolko** [comment]
Hey Ben.

**Comment by amitaymolko** [comment]
Hey Ben,

I have tested this MR and it seems to be working well.
This MR increases the minimal React Native version so I'm considering releasing it as a new major version to not affect current users of the lib.
I'm aware that this MR also fixes known issues with newer RN versions.
I will do my best to get to this ASAP.

Cheers

**Comment by Ben305** [comment]
A new major version would be perfectly fine, I‘d like to use this package for a new app based on RN 0.62.

**Comment by amitaymolko** [comment]
merging into a branch to fix the example project and docs, and then I will release a version

**Comment by amitaymolko** [comment]
After fixing the example project and 2 small issues I've released this under v2.0.0

**Comment by Ben305** [comment]
Thank you @amitaymolko

**Pull request merged**
