### PR TITLE
Support deleting a private key

### PR DESCRIPTION
**Pull request by crafterm**
Hi @amitaymolko 

Mate, hope all is going well - this PR adds support for deleting the generated private key from the keychain (or memory). Have added the iOS implementation. Hopefully the Android side is similar as well?

Thanks mate. Talk soon!

Cheers,

Marcus

### CODE REVIEW

**Comment by amitaymolko** [comment]
Thanks man!
You make me very happy when you submit a PR :)

I have published a release (1.0.12)

**Comment by amitaymolko** [comment]
I will add the Android implementation a little later

**Comment by amitaymolko** [comment]
Ok, I've added android support and release v1.0.13

**Comment by crafterm** [comment]
@amitaymolko mate, you're a legend! thanks for adding the Android support and pushing out a new release!

Love working on the project, keep up the awesome mate! Fantastic

Cheers!

**Pull request merged**
