### PR TITLE
[WIP] Sign/verify iOS implementation

### PR DESCRIPTION
**Pull request by crafterm**
Hi @amitaymolko 

Hope all is going well mate.

Here's the iOS implementation methods required to create and verify digital signatures of content for both the keychain and in-memory store modules.

Please have a look and let me know if you're happy with the implementation. Have also updated the README with some examples - happy to adjust into the API you're considering as mentioned in the previous PR now or later.

Keen to get the Android side sorted so we can have parity across the platforms - not too sure where to start but let me know if you'd like me to look into that?

Hear from you soon then - Cheers.

### CODE REVIEW

**Comment by amitaymolko** [comment]
Hey @crafterm 

Great job, 

Went over commits generally looks good
Will test and add android support before merging
Not sure when I will have time, hopefully before the weekend

**Comment by amitaymolko** [comment]
@crafterm added android signature support
please notice i have dropped the RN in the import, but kept the old ones as well so it doesn't break older code

**Comment by amitaymolko** [comment]
This accidentally merged into master and not into develop, sorry for the inconvenience...

**Comment by crafterm** [comment]
@amitaymolko thanks mate, awesome stuff on the Android side too! thanks for rolling and publishing a new version too!

**Pull request merged**
