### PR TITLE
[WIP] Update to use Apple Sec* crypto methods with keychain storage

### PR DESCRIPTION
**Pull request by crafterm**
Hi @amitaymolko, (cc @aaronbuchanan)

Please have a look at the changes here - its a WIP but I've updated the iOS side to use the Apple Sec* methods for key generation, encryption, decryption, and extraction for external representation. Keen to get your feedback before pushing on too much further.

I've also updated the README with updated instructions that no longer require cocoapods.

The code I've got in place also will also write the private key into the iOS keychain, and access it from there when encrypting or decrypting. This is here's where the method signatures differ from master where by instead of passing the literal key through, the methods are accepting a keychain tag string.

Its still possible to support the older API of passing the literal keys in however I'll need to adjust these newer method names to not conflict at the JS level with the original ones. I wanted to double check with you first if thats the direction you're keen on heading?

Haven't looked at the Android side yet regarding keystore/chain equivalents but have found some documentation to dig further into - at first glance there's a compatible thing available.

All use cases on the iOS side are working fine here in my test application.

Let me know your thoughts after you've had a peruse - hear from you soon.

Cheers

### CODE REVIEW

**Comment by crafterm** [comment]
Hi @amitaymolko - just updated the PR to include support for both API styles, ie. keychain and the original memory storage based API. Currently implemented via 2 modules one with a keychain suffix - you might have a better idea?

Again WIP - keen to hear what you think. All working locally nicely.

**Comment by amitaymolko** [comment]
Great job 👍 
I went over the code generally its good, will test soon.
I would like to keep previous string functionality, also until we add android keychain support its best to have the methods the same in iOS/android
I will adjust the PR accordingly

**Comment by crafterm** [comment]
Thanks mate, the previous string functionality should also work as before now - essentially the iOS code side is looking for an internal keychain tag property, if that exists, its assuming keychain access, and if missing, it looks for the keys in local memory properties.

I'm less familiar on the Android side but reading (here)[http://www.androidauthority.com/use-android-keystore-store-passwords-sensitive-information-623779/] looks like there's similar concepts and its called an alias/keystore as opposed to tag/keychain.

Definitely agree the android keychain support should have the same methods, functionality too - we will require that here as well. 

Keen to hear your thoughts on the module split (ie. RNRSA & RNRSAKeychain), perhaps there's a better way (or just more unique method signatures in the one module?)

Let me know mate how best we proceed and what we need to sort out to be confident in merging.

**Comment by crafterm** [comment]
btw - have added you as a collaborator to my fork to make it easier in case you'd like to push any commits to the same PR.

**Comment by amitaymolko** [comment]
@crafterm A few things i would like to discuss:
1. Keychain Import private key method. I think this will be necessary 
2. PKCS#1 support (and pem header) currently iOS doesn't have any padding, do you need specific padding? I would like PKCS#1, but we can also support multiple paddings
3. Sign/Verify methods? Personally I think this feature can wait
4. Method structure:
Maybe we should export more core methods in the package so user can do something like this:
```
const exampleRsaStuff = async () => {

    const rsa = await RSA.init();
    await rsa.generate;

    const rsa = await RSA.initWithTag(keyTag)
    await rsa.generate;

    const publicKey = await rsa.exportPublicKey(padding?) // can support multiple padding? default PKCS#1
    const privateKey = await rsa.exportPrivateKey(padding?) // support both chain and string
    const keys = await rsa.exportKeys(padding?) 

    await rsa.importPublicKey(privateKey, padding?)
    await rsa.importPrivateKey(privateKey, padding?)
    await rsa.save(keyTag)

    const encryptedMessage = await rsa.encrypt(message)
    const message = await rsa.decrypt(encryptedMessage)

    const signed = await rsa.sign(body)
    const body = await rsa.verify(signed)

}; 

```
The annoying thing about exporting more methods is that every react native module call returns a promise, buts its not bad in an async function
Or we can go with somethings like this:
```
RSA.generate(padding?)
RSA.encrypt(message, publicKey, padding?) // or publicKey can be { key, padding}
RSA.decrypt(message, privateKey, padding?)
RSA.sign(body, privateKey)
RSA.verify(body, publicKey)

RSA.chain.generate(keyTag, padding?)
RSA.chain.encrypt(message, keyTag, padding?)
RSA.chain.decrypt(message, keyTag, padding?)
RSA.chain.sign(message, keyTag, padding?)
RSA.chain.verify(message, keyTag, padding?)
RSA.chain.import(keyTag, privateKey)

```

Thoughts?
I have also added you as a collaborator, I think that will be easiest going forward :)

**Comment by amitaymolko** [comment]
I added pem format, and changed to PKCS#1 format
Currently supported headers are "RSA PUBLIC" & "RSA PRIVATE".
**IT Doesn't support  "-----BEGIN PUBLIC KEY-----" header (even PKCS#1)** this might be introduced in the future

Also i have defaulted to the non keychain rsa implementation until we figure out the method structure we want and introduce an android keychain implementation

**Comment by amitaymolko** [comment]
Ok I'm merging so I can push a new version to npm.
Will also create a develop branch so we can keep master consistent with npm

**Comment by crafterm** [comment]
@amitaymolko thanks mate for the collaborator bit and develop is perfect for future dev work to keep master in sync with npm.

Happy with the default being the non-keychain version for the moment till we work out Android, I'll dig a bit deeper with the Android docs around the key store, i'm less familiar with Android than iOS, if you (or anyone else reading) have any pointers let me know.

Great work on the PEM format, and PKCS#1 is also fine with me too. If we need more flexibility in the future, I'm sure we can make the algorithm configurable.

RSAFormatter looks good - thanks for putting it in the xcodeproj file as well.

I agree with you on sign/verify, can come later I think as well.

Both API styles look good mate, do you have a preference for either one?

**Comment by amitaymolko** [comment]
@crafterm 
I can add the android keychain support.
But first we need to decide what the method structure should be.

I will think about this some more and post back here

**Comment by crafterm** [comment]
@amitaymolko thanks mate, sounds good on the android keychain side.

Turns out we'll need support for signatures here so i'll put together some thoughts on getting this working as well

Hear from you soon then on the method structure

**Pull request merged**
